output_dir: xyz_opt 
base_structures: /beegfs/coldpool/htphan/sugar/disaccharides/replace_and_rotate/bGal_14_aGlcNAc/find_structure_bh_ext/base_structure/neutral_di_nnp_minima.lst 
seed_structure: /beegfs/coldpool/htphan/fragment/C_NAc/C_NAc.xyz 
temperature: 0.132 
max_rejected: 10
save_trajectories: true
steps: 5 
operations: [flip, attach_rotate, add_proton]
model:
  state_dict: /beegfs/coldpool/htphan/sugar_4/schnetpack_proj/force_pred/m062x_6-311_gpd/find_structure_di/10_add_ext_H_position/01_add_bGal_14_bGlcNAc/cl_learning_lr_5e-4_resume/best_model
  prop_stats: null
  device: cpu
  in_module: {n_atom_basis: 128, n_filters: 128, n_gaussians: 75, charged_systems: true, n_interactions: 4,
    cutoff: 15.0}
  interface_params: {energy: energy, forces: force, energy_units: Hartree, forces_units: Hartree/Angstrom}
optimization: {fmax: 0.005, steps: 1000}
physical_check:
  enabled: true
  params: {CO_min_threshold: 1.2, CH_min_threshold: 0.88, OO_min_threshold: 1.62, OH_min_threshold: 0.85,
    NC_min_threshold: 1.2, NO_min_threshold: 1.62, NH_min_threshold: 0.73, HH_min_threshold: 0.66}
flip_grid: [0, 120, 240]
attach_rotate_grid: [0, 60, 120, 180, 240, 300]
proton_grid:
- [16, -130, OCC]
- [16, 130, OCC]
- [0, -130, OCC]
- [0, 130, OCC]
- [21, -120, OCH]
- [21, 120, OCH]
- [19, -120, OCH]
- [19, 120, OCH]
- [17, -120, OCH]
- [17, 120, OCH]
- [14, -120, OCH]
- [14, 120, OCH]
- [39, -130, OCC]
- [39, 130, OCC]
- [24, -120, OCH]
- [24, 120, OCH]
- [43, -67.5, N]
- [43, 67.5, N]
- [50, 0, OC]
- [50, 60, OC]
- [50, 120, OC]
- [50, 180, OC]
- [50, 240, OC]
- [50, 300, OC]
- [40, -120, OCH]
- [40, 120, OCH]
- [37, -120, OCH]
- [37, 120, OCH]
logging: {level: INFO, file: basin_hopping.log}
